### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dfandrich** [fragglet/lhasa#44]
Are there plans to make a new release? There have been a few crash and overflow fixes committed in the last 7 (!) years. Most user won't get those without an actual release.

**Comment by fragglet** [comment]
That does indeed sound like a good idea. Although in fairness there haven't been all that many changes in the past 7 years.

**Comment by tsutsui** [comment]
As a package system maintainer, an explicit release (tag) is appreciated to get rid of package system local patches.
https://github.com/NetBSD/pkgsrc/tree/9bbe089e/archivers/lhasa/patches

**Comment by fragglet** [comment]
Message received folks, thanks. I just put out the 0.4.0 release.

**Comment by tsutsui** [comment]
I've also updated pkgsrc/archivers/lhasa. Thanks!
https://mail-index.netbsd.org/pkgsrc-changes/2023/05/14/msg274751.html
